provinces = {
    1:  {"tr": "Adana",          "en": "Adana",             "gadm": "Adana"},
    2:  {"tr": "Adıyaman",       "en": "Adiyaman",          "gadm": "Adiyaman"},
    3:  {"tr": "Afyonkarahisar", "en": "Afyonkarahisar",    "gadm": "Afyon"},
    4:  {"tr": "Ağrı",           "en": "Agri"},
    5:  {"tr": "Amasya",         "en": "Amasya"},
    6:  {"tr": "Ankara",         "en": "Ankara"},
    7:  {"tr": "Antalya",        "en": "Antalya"},
    8:  {"tr": "Artvin",         "en": "Artvin"},
    9:  {"tr": "Aydın",          "en": "Aydin"},
    10: {"tr": "Balıkesir",      "en": "Balikesir"},
    11: {"tr": "Bilecik",        "en": "Bilecik"},
    12: {"tr": "Bingöl",         "en": "Bingol",            "gadm": "Bingöl"},
    13: {"tr": "Bitlis",         "en": "Bitlis"},
    14: {"tr": "Bolu",           "en": "Bolu"},
    15: {"tr": "Burdur",         "en": "Burdur"},
    16: {"tr": "Bursa",          "en": "Bursa"},
    17: {"tr": "Çanakkale",      "en": "Canakkale",         "gadm": "Çanakkale"},
    18: {"tr": "Çankırı",        "en": "Cankiri",           "gadm": "Çankiri"},
    19: {"tr": "Çorum",          "en": "Corum",             "gadm": "Çorum"},
    20: {"tr": "Denizli",        "en": "Denizli"},
    21: {"tr": "Diyarbakır",     "en": "Diyarbakir"},
    22: {"tr": "Edirne",         "en": "Edirne"},
    23: {"tr": "Elazığ",         "en": "Elazig",            "gadm": "Elazığ"},
    24: {"tr": "Erzincan",       "en": "Erzincan"},
    25: {"tr": "Erzurum",        "en": "Erzurum"},
    26: {"tr": "Eskişehir",      "en": "Eskisehir"},
    27: {"tr": "Gaziantep",      "en": "Gaziantep"},
    28: {"tr": "Giresun",        "en": "Giresun"},
    29: {"tr": "Gümüşhane",      "en": "Gumushane",         "gadm": "Gümüshane"},
    30: {"tr": "Hakkari",        "en": "Hakkari"},
    31: {"tr": "Hatay",          "en": "Hatay"},
    32: {"tr": "Isparta",        "en": "Isparta"},
    33: {"tr": "Mersin",         "en": "Mersin"},
    34: {"tr": "İstanbul",       "en": "Istanbul"},
    35: {"tr": "İzmir",          "en": "Izmir"},
    36: {"tr": "Kars",           "en": "Kars"},
    37: {"tr": "Kastamonu",      "en": "Kastamonu"},
    38: {"tr": "Kayseri",        "en": "Kayseri"},
    39: {"tr": "Kırklareli",     "en": "Kirklareli"},
    40: {"tr": "Kırşehir",       "en": "Kirsehir"},
    41: {"tr": "Kocaeli",        "en": "Kocaeli"},
    42: {"tr": "Konya",          "en": "Konya"},
    43: {"tr": "Kütahya",        "en": "Kutahya",           "gadm": "Kütahya"},
    44: {"tr": "Malatya",        "en": "Malatya"},
    45: {"tr": "Manisa",         "en": "Manisa"},
    46: {"tr": "Kahramanmaraş",  "en": "Kahramanmaras",     "gadm": "K. Maras"},
    47: {"tr": "Mardin",         "en": "Mardin"},
    48: {"tr": "Muğla",          "en": "Mugla"},
    49: {"tr": "Muş",            "en": "Mus"},
    50: {"tr": "Nevşehir",       "en": "Nevsehir"},
    51: {"tr": "Niğde",          "en": "Nigde"},
    52: {"tr": "Ordu",           "en": "Ordu"},
    53: {"tr": "Rize",           "en": "Rize"},
    54: {"tr": "Sakarya",        "en": "Sakarya"},
    55: {"tr": "Samsun",         "en": "Samsun"},
    56: {"tr": "Siirt",          "en": "Siirt"},
    57: {"tr": "Sinop",          "en": "Sinop"},
    58: {"tr": "Sivas",          "en": "Sivas"},
    59: {"tr": "Tekirdağ",       "en": "Tekirdag"},
    60: {"tr": "Tokat",          "en": "Tokat"},
    61: {"tr": "Trabzon",        "en": "Trabzon"},
    62: {"tr": "Tunceli",        "en": "Tunceli"},
    63: {"tr": "Şanlıurfa",      "en": "Sanliurfa"},
    64: {"tr": "Uşak",           "en": "Usak"},
    65: {"tr": "Van",            "en": "Van"},
    66: {"tr": "Yozgat",         "en": "Yozgat"},
    67: {"tr": "Zonguldak",      "en": "Zonguldak",         "gadm": "Zinguldak"},
    68: {"tr": "Aksaray",        "en": "Aksaray"},
    69: {"tr": "Bayburt",        "en": "Bayburt"},
    70: {"tr": "Karaman",        "en": "Karaman"},
    71: {"tr": "Kırıkkale",      "en": "Kirikkale",         "gadm": "Kinkkale"},
    72: {"tr": "Batman",         "en": "Batman"},
    73: {"tr": "Şırnak",         "en": "Sirnak"},
    74: {"tr": "Bartın",         "en": "Bartin",           "gadm": "Bartın"},
    75: {"tr": "Ardahan",        "en": "Ardahan"},
    76: {"tr": "Iğdır",          "en": "Igdir",             "gadm": "Iğdır"},
    77: {"tr": "Yalova",         "en": "Yalova"},
    78: {"tr": "Karabük",        "en": "Karabuk",           "gadm": "Karabük"},
    79: {"tr": "Kilis",          "en": "Kilis"},
    80: {"tr": "Osmaniye",       "en": "Osmaniye"},
    81: {"tr": "Düzce",          "en": "Duzce",             "gadm": "Düzce"},
}

tr_to_id = {v["tr"]: k for k, v in provinces.items()}
en_to_id = {v["en"]: k for k, v in provinces.items()}
id_to_tr = {k: v["tr"] for k, v in provinces.items()}
id_to_en = {k: v["en"] for k, v in provinces.items()}
id_to_gadm = {k: v.get("gadm", v["en"]) for k, v in provinces.items()}
gadm_to_id = {v.get("gadm", v["en"]): k for k, v in provinces.items()}